/*
 * This file is part of the Illarion project.
 *
 * Copyright © 2015 - Illarion e.V.
 *
 * Illarion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Illarion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply from: '../versions.gradle'

dependencies {
    api project(':engine')
    api project(':common')
    api group: 'com.badlogicgames.gdx', name: 'gdx', version: '1.10.0'
    implementation group: 'com.badlogicgames.gdx', name: 'gdx-backend-lwjgl3', version: '1.10.0'
    implementation group: 'com.badlogicgames.gdx', name: 'gdx-platform', version: '1.10.0', classifier: 'natives-desktop'
    implementation group: 'com.google.guava', name: 'guava', version: '30.1.1-jre'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
}

jar {
    manifest {
        attributes(
                'Permissions': 'all-permissions',
                'Codebase': 'illarion.org',
                'Trusted-Library': true,
                'Built-Date': new Date().format('yyyy-MM-dd HH:mm:ssZ'),
                'Built-By': System.getProperty('user.name'),
                'Built-JDK': System.getProperty('java.version'),
                'Implementation-Title': 'Illarion Game Engine - libGDX Backend',
                'Implementation-Vendor': 'Illarion e.V.',
                'Implementation-Version': project.ext.fullVersion
        )
    }
}
